apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kp31h2svv-go 
  janus-idp.io/tekton: kp31h2svv-go
  backstage.io/kubernetes-id: kp31h2svv-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kp31h2svv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml