apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kp31h2svv-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:803b30296b429d3e98737dc52f5dbce274418087@sha256:45b8ebc686da9fc562aa314374dd4fd02ebbb050fb8fbffe8fa35489b0e72a56
          name: container-image
